// Archived from the Pixelblaze 2026-08-22
// Device pattern name: Aura-World
// Pattern id: pcdZDxs43mzcor3b8
// Taken by tools/archive_patterns.py before pruning the
// device's flash. This file is a copy, not the source of
// truth -- nothing in this project builds it.

// Aura-World -- GENERATED by tools/patterngen.py. Do not edit here.
// Standalone aura, played when no scene is running.
segStart = [ 60, 502,  0, 705, 180, 240, 120, 443]
segLen   = [ 60, 203, 60,  59,  60, 203,  60,  59]
pathPos = array(pixelCount)
for (i = 0; i < pixelCount; i++) pathPos[i] = -1
pathLen = 0
for (s = 0; s < 8; s++) {
  for (k = 0; k < segLen[s]; k++) {
    idx = segStart[s] + k
    if (idx < pixelCount) { pathPos[idx] = pathLen; pathLen = pathLen + 1 }
  }
}
hA = 0
hB = 0
sA = 0.9
sB = 0.9
vA = 0.04
vB = 0.6
hueShift = 0
export function beforeRender(delta) {
  dt = delta / 1000
  env = 0.45 + 0.55 * wave(time(0.16785))
  hueShift = time(0.91553)
}
export function render(index) {
  p = pathPos[index]
  if (p < 0) { rgb(0, 0, 0); return }
  u = p / pathLen
  raw = 1
  f = raw
  h = hA + (hB - hA) * (f)
  sa = sA + (sB - sA) * (f)
  v = vA + (vB - vA) * (f)
  h = h + hueShift
  v = v * env
  hsv(h, sa, v)
}
