// Archived from the Pixelblaze 2026-08-22
// Device pattern name: Aura-Star
// Pattern id: oZSgJDihxfEq2JJvn
// Taken by tools/archive_patterns.py before pruning the
// device's flash. This file is a copy, not the source of
// truth -- nothing in this project builds it.

// Aura-Star -- GENERATED by tools/patterngen.py. Do not edit here.
// Standalone aura, played when no scene is running.
segStart = [ 60, 502,  0, 705, 180, 240, 120, 443]
segLen   = [ 60, 203, 60,  59,  60, 203,  60,  59]
pathPos = array(pixelCount)
for (i = 0; i < pixelCount; i++) pathPos[i] = -1
pathLen = 0
for (s = 0; s < 8; s++) {
  for (k = 0; k < segLen[s]; k++) {
    idx = segStart[s] + k
    if (idx < pixelCount) { pathPos[idx] = pathLen; pathLen = pathLen + 1 }
  }
}
hA = 0.55
hB = 0.55
sA = 0.35
sB = 0.35
vA = 0.04
vB = 0.6
N = 9
bWide = 4
bGain = 0.9
bMin = 0.5
bVar = 1.2
bRest = 1.5
bHue = 0.55
bPos = array(N)
bAge = array(N)
bLife = array(N)
for (i = 0; i < N; i++) {
  bPos[i] = random(pathLen)
  bLife[i] = bMin + random(bVar)
  bAge[i] = random(bLife[i])
}
export function beforeRender(delta) {
  dt = delta / 1000
  env = 1
  for (i = 0; i < N; i++) {
    bAge[i] = bAge[i] + dt
    if (bAge[i] >= bLife[i]) {
      bAge[i] = -random(bRest)
      bLife[i] = bMin + random(bVar)
      bPos[i] = random(pathLen)
    }
  }
}
export function render(index) {
  p = pathPos[index]
  if (p < 0) { rgb(0, 0, 0); return }
  u = p / pathLen
  raw = 1
  f = raw
  h = hA + (hB - hA) * (f)
  sa = sA + (sB - sA) * (f)
  v = vA + (vB - vA) * (f)
  b = 0
  for (j = 0; j < N; j++) {
    if (bAge[j] > 0) {
      dd = p - bPos[j]
      dd = dd - pathLen * floor(dd / pathLen + 0.5)
      dd = abs(dd)
      if (dd < bWide) {
        fall = 1 - dd / bWide
        e = 1 - bAge[j] / bLife[j]
        b = b + fall * e * e * bGain
      }
    }
  }
  if (b > 0) {
    bk = min(b, 1)
    h = h + (bHue - h) * bk
    v = v + b
  }
  v = v * env
  hsv(h, sa, v)
}
