// Archived from the Pixelblaze 2026-08-22
// Device pattern name: Forest+Strength
// Pattern id: SqTEcjPgY3e9H6S7T
// Taken by tools/archive_patterns.py before pruning the
// device's flash. This file is a copy, not the source of
// truth -- nothing in this project builds it.

// Forest+Strength -- GENERATED by tools/patterngen.py. Do not edit here.
// Forest under the Strength aura.
segStart = [ 60, 502,  0, 705, 180, 240, 120, 443]
segLen   = [ 60, 203, 60,  59,  60, 203,  60,  59]
pathPos = array(pixelCount)
for (i = 0; i < pixelCount; i++) pathPos[i] = -1
pathLen = 0
for (s = 0; s < 8; s++) {
  for (k = 0; k < segLen[s]; k++) {
    idx = segStart[s] + k
    if (idx < pixelCount) { pathPos[idx] = pathLen; pathLen = pathLen + 1 }
  }
}
wfA = 3
wsA = 0.16
wfB = 7
wsB = 0.26
hA = 0.168
hB = 0.141
sA = 0.909
sB = 0.909
vA = 0.05
vB = 0.4
N = 3
bWide = 70
bGain = 0.55
bMin = 5
bVar = 6
bPos = array(N)
bAge = array(N)
bLife = array(N)
for (i = 0; i < N; i++) {
  bPos[i] = random(pathLen)
  bLife[i] = bMin + random(bVar)
  bAge[i] = random(bLife[i])
}
export function beforeRender(delta) {
  dt = delta / 1000
  tA = time(wsA)
  tB = time(wsB)
  et = time(0.03662)
  env = 0.35
  if (et < 0.12) env = 1 - (1 - 0.35) * (et / 0.12)
  if (et > 0.20 && et < 0.34) env = 0.35 + 0.455 * (1 - (et - 0.20) / 0.14)
  for (i = 0; i < N; i++) {
    bAge[i] = bAge[i] + dt
    if (bAge[i] >= bLife[i]) {
      bAge[i] = 0
      bLife[i] = bMin + random(bVar)
      bPos[i] = random(pathLen)
    }
  }
}
export function render(index) {
  p = pathPos[index]
  if (p < 0) { rgb(0, 0, 0); return }
  u = p / pathLen
  raw = wave(u * wfA + tA) * 0.6 + wave(u * wfB - tB) * 0.4
  f = raw * raw
  b = 0
  for (j = 0; j < N; j++) {
    dd = p - bPos[j]
    dd = dd - pathLen * floor(dd / pathLen + 0.5)
    dd = abs(dd)
    if (dd < bWide) {
      fall = 1 - dd / bWide
      e = triangle(bAge[j] / bLife[j])
      b = b + fall * fall * e * e * bGain
    }
  }
  f = min(f + b, 1)
  h = hA + (hB - hA) * (f)
  sa = sA + (sB - sA) * (f)
  v = vA + (vB - vA) * (f)
  sa = sa - 0.25 * min(b, 1)
  v = v * env
  hsv(h, sa, v)
}
