// Archived from the Pixelblaze 2026-08-22
// Device pattern name: Island
// Pattern id: PNSzGHdspMvcQRNqN
// Taken by tools/archive_patterns.py before pruning the
// device's flash. This file is a copy, not the source of
// truth -- nothing in this project builds it.

// Island -- GENERATED by tools/patterngen.py. Do not edit here.
// Swell with foam on the crests.
segStart = [ 60, 502,  0, 705, 180, 240, 120, 443]
segLen   = [ 60, 203, 60,  59,  60, 203,  60,  59]
pathPos = array(pixelCount)
for (i = 0; i < pixelCount; i++) pathPos[i] = -1
pathLen = 0
for (s = 0; s < 8; s++) {
  for (k = 0; k < segLen[s]; k++) {
    idx = segStart[s] + k
    if (idx < pixelCount) { pathPos[idx] = pathLen; pathLen = pathLen + 1 }
  }
}
wfA = 2
wsA = 0.1
wfB = 3
wsB = 0.07
hA = 0.55
hB = 0.48
sA = 0.95
sB = 0.45
vA = 0.05
vB = 0.42
thr = 0.88
thrGain = 0.35
export function beforeRender(delta) {
  dt = delta / 1000
  tA = time(wsA)
  tB = time(wsB)
}
export function render(index) {
  p = pathPos[index]
  if (p < 0) { rgb(0, 0, 0); return }
  u = p / pathLen
  raw = wave(u * wfA - tA) * 0.55 + wave(u * wfB + tB) * 0.45
  f = raw
  h = hA + (hB - hA) * (f * f * f)
  sa = sA + (sB - sA) * (f * f * f)
  v = vA + (vB - vA) * (f * f)
  if (raw > thr) {
    t = (raw - thr) / (1 - thr)
    v = v + t * t * thrGain
    sa = sa * (1 - 0.6 * t)
  }
  hsv(h, sa, v)
}
