// Archived from the Pixelblaze 2026-08-22
// Device pattern name: Plains
// Pattern id: x2WTg2mcHu7F5jEuc
// Taken by tools/archive_patterns.py before pruning the
// device's flash. This file is a copy, not the source of
// truth -- nothing in this project builds it.

// Plains -- GENERATED by tools/patterngen.py. Do not edit here.
// Broad soft gusts over ripe grain.
segStart = [ 60, 502,  0, 705, 180, 240, 120, 443]
segLen   = [ 60, 203, 60,  59,  60, 203,  60,  59]
pathPos = array(pixelCount)
for (i = 0; i < pixelCount; i++) pathPos[i] = -1
pathLen = 0
for (s = 0; s < 8; s++) {
  for (k = 0; k < segLen[s]; k++) {
    idx = segStart[s] + k
    if (idx < pixelCount) { pathPos[idx] = pathLen; pathLen = pathLen + 1 }
  }
}
wfA = 1
wsA = 0.5
wfB = 2
wsB = 0.35
hA = 0.13
hB = 0.1
sA = 0.62
sB = 0.88
vA = 0.18
vB = 0.5
export function beforeRender(delta) {
  dt = delta / 1000
  tA = time(wsA)
  tB = time(wsB)
}
export function render(index) {
  p = pathPos[index]
  if (p < 0) { rgb(0, 0, 0); return }
  u = p / pathLen
  raw = wave(u * wfA - tA) * 0.6 + wave(u * wfB - tB) * 0.4
  f = raw * raw * (3 - 2 * raw)
  h = hA + (hB - hA) * (f)
  sa = sA + (sB - sA) * (f)
  v = vA + (vB - vA) * (f)
  hsv(h, sa, v)
}
